// flow-typed signature: a591baeef9ad390529d6ba8e2ad4cabc
// flow-typed version: <<STUB>>/ethers_v^3.0.9/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethers/contracts/contract' {
  declare module.exports: any;
}

declare module 'ethers/contracts/index' {
  declare module.exports: any;
}

declare module 'ethers/contracts/interface' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-contracts' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-contracts.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-providers' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-providers.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-utils' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-utils.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-wallet' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-wallet.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers.min' {
  declare module.exports: any;
}

declare module 'ethers/providers/browser-xmlhttprequest' {
  declare module.exports: any;
}

declare module 'ethers/providers/etherscan-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/fallback-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/index' {
  declare module.exports: any;
}

declare module 'ethers/providers/infura-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/json-rpc-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/web3-provider' {
  declare module.exports: any;
}

declare module 'ethers/utils/abi-coder' {
  declare module.exports: any;
}

declare module 'ethers/utils/address' {
  declare module.exports: any;
}

declare module 'ethers/utils/bignumber' {
  declare module.exports: any;
}

declare module 'ethers/utils/browser-random-bytes' {
  declare module.exports: any;
}

declare module 'ethers/utils/contract-address' {
  declare module.exports: any;
}

declare module 'ethers/utils/convert' {
  declare module.exports: any;
}

declare module 'ethers/utils/hmac' {
  declare module.exports: any;
}

declare module 'ethers/utils/id' {
  declare module.exports: any;
}

declare module 'ethers/utils/index' {
  declare module.exports: any;
}

declare module 'ethers/utils/keccak256' {
  declare module.exports: any;
}

declare module 'ethers/utils/namehash' {
  declare module.exports: any;
}

declare module 'ethers/utils/pbkdf2' {
  declare module.exports: any;
}

declare module 'ethers/utils/properties' {
  declare module.exports: any;
}

declare module 'ethers/utils/random-bytes' {
  declare module.exports: any;
}

declare module 'ethers/utils/rlp' {
  declare module.exports: any;
}

declare module 'ethers/utils/sha2' {
  declare module.exports: any;
}

declare module 'ethers/utils/solidity' {
  declare module.exports: any;
}

declare module 'ethers/utils/throw-error' {
  declare module.exports: any;
}

declare module 'ethers/utils/units' {
  declare module.exports: any;
}

declare module 'ethers/utils/utf8' {
  declare module.exports: any;
}

declare module 'ethers/wallet/hdnode' {
  declare module.exports: any;
}

declare module 'ethers/wallet/index' {
  declare module.exports: any;
}

declare module 'ethers/wallet/secret-storage' {
  declare module.exports: any;
}

declare module 'ethers/wallet/signing-key' {
  declare module.exports: any;
}

declare module 'ethers/wallet/wallet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethers/contracts/contract.js' {
  declare module.exports: $Exports<'ethers/contracts/contract'>;
}
declare module 'ethers/contracts/index.js' {
  declare module.exports: $Exports<'ethers/contracts/index'>;
}
declare module 'ethers/contracts/interface.js' {
  declare module.exports: $Exports<'ethers/contracts/interface'>;
}
declare module 'ethers/dist/ethers-contracts.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-contracts'>;
}
declare module 'ethers/dist/ethers-contracts.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-contracts.min'>;
}
declare module 'ethers/dist/ethers-providers.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-providers'>;
}
declare module 'ethers/dist/ethers-providers.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-providers.min'>;
}
declare module 'ethers/dist/ethers-utils.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-utils'>;
}
declare module 'ethers/dist/ethers-utils.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-utils.min'>;
}
declare module 'ethers/dist/ethers-wallet.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-wallet'>;
}
declare module 'ethers/dist/ethers-wallet.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-wallet.min'>;
}
declare module 'ethers/dist/ethers.js' {
  declare module.exports: $Exports<'ethers/dist/ethers'>;
}
declare module 'ethers/dist/ethers.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.min'>;
}
declare module 'ethers/index' {
  declare module.exports: $Exports<'ethers'>;
}
declare module 'ethers/index.js' {
  declare module.exports: $Exports<'ethers'>;
}
declare module 'ethers/providers/browser-xmlhttprequest.js' {
  declare module.exports: $Exports<'ethers/providers/browser-xmlhttprequest'>;
}
declare module 'ethers/providers/etherscan-provider.js' {
  declare module.exports: $Exports<'ethers/providers/etherscan-provider'>;
}
declare module 'ethers/providers/fallback-provider.js' {
  declare module.exports: $Exports<'ethers/providers/fallback-provider'>;
}
declare module 'ethers/providers/index.js' {
  declare module.exports: $Exports<'ethers/providers/index'>;
}
declare module 'ethers/providers/infura-provider.js' {
  declare module.exports: $Exports<'ethers/providers/infura-provider'>;
}
declare module 'ethers/providers/json-rpc-provider.js' {
  declare module.exports: $Exports<'ethers/providers/json-rpc-provider'>;
}
declare module 'ethers/providers/provider.js' {
  declare module.exports: $Exports<'ethers/providers/provider'>;
}
declare module 'ethers/providers/web3-provider.js' {
  declare module.exports: $Exports<'ethers/providers/web3-provider'>;
}
declare module 'ethers/utils/abi-coder.js' {
  declare module.exports: $Exports<'ethers/utils/abi-coder'>;
}
declare module 'ethers/utils/address.js' {
  declare module.exports: $Exports<'ethers/utils/address'>;
}
declare module 'ethers/utils/bignumber.js' {
  declare module.exports: $Exports<'ethers/utils/bignumber'>;
}
declare module 'ethers/utils/browser-random-bytes.js' {
  declare module.exports: $Exports<'ethers/utils/browser-random-bytes'>;
}
declare module 'ethers/utils/contract-address.js' {
  declare module.exports: $Exports<'ethers/utils/contract-address'>;
}
declare module 'ethers/utils/convert.js' {
  declare module.exports: $Exports<'ethers/utils/convert'>;
}
declare module 'ethers/utils/hmac.js' {
  declare module.exports: $Exports<'ethers/utils/hmac'>;
}
declare module 'ethers/utils/id.js' {
  declare module.exports: $Exports<'ethers/utils/id'>;
}
declare module 'ethers/utils/index.js' {
  declare module.exports: $Exports<'ethers/utils/index'>;
}
declare module 'ethers/utils/keccak256.js' {
  declare module.exports: $Exports<'ethers/utils/keccak256'>;
}
declare module 'ethers/utils/namehash.js' {
  declare module.exports: $Exports<'ethers/utils/namehash'>;
}
declare module 'ethers/utils/pbkdf2.js' {
  declare module.exports: $Exports<'ethers/utils/pbkdf2'>;
}
declare module 'ethers/utils/properties.js' {
  declare module.exports: $Exports<'ethers/utils/properties'>;
}
declare module 'ethers/utils/random-bytes.js' {
  declare module.exports: $Exports<'ethers/utils/random-bytes'>;
}
declare module 'ethers/utils/rlp.js' {
  declare module.exports: $Exports<'ethers/utils/rlp'>;
}
declare module 'ethers/utils/sha2.js' {
  declare module.exports: $Exports<'ethers/utils/sha2'>;
}
declare module 'ethers/utils/solidity.js' {
  declare module.exports: $Exports<'ethers/utils/solidity'>;
}
declare module 'ethers/utils/throw-error.js' {
  declare module.exports: $Exports<'ethers/utils/throw-error'>;
}
declare module 'ethers/utils/units.js' {
  declare module.exports: $Exports<'ethers/utils/units'>;
}
declare module 'ethers/utils/utf8.js' {
  declare module.exports: $Exports<'ethers/utils/utf8'>;
}
declare module 'ethers/wallet/hdnode.js' {
  declare module.exports: $Exports<'ethers/wallet/hdnode'>;
}
declare module 'ethers/wallet/index.js' {
  declare module.exports: $Exports<'ethers/wallet/index'>;
}
declare module 'ethers/wallet/secret-storage.js' {
  declare module.exports: $Exports<'ethers/wallet/secret-storage'>;
}
declare module 'ethers/wallet/signing-key.js' {
  declare module.exports: $Exports<'ethers/wallet/signing-key'>;
}
declare module 'ethers/wallet/wallet.js' {
  declare module.exports: $Exports<'ethers/wallet/wallet'>;
}
