// flow-typed signature: bb59eb9187bd093921290d795bbdddfd
// flow-typed version: <<STUB>>/ethers_vhttps://github.com/jsidorenko/ethers.js#master/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethers/_version' {
  declare module.exports: any;
}

declare module 'ethers/abstract-signer' {
  declare module.exports: any;
}

declare module 'ethers/constants' {
  declare module.exports: any;
}

declare module 'ethers/contract' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/shims' {
  declare module.exports: any;
}

declare module 'ethers/dist/wordlist-es' {
  declare module.exports: any;
}

declare module 'ethers/dist/wordlist-fr' {
  declare module.exports: any;
}

declare module 'ethers/dist/wordlist-it' {
  declare module.exports: any;
}

declare module 'ethers/dist/wordlist-ja' {
  declare module.exports: any;
}

declare module 'ethers/dist/wordlist-ko' {
  declare module.exports: any;
}

declare module 'ethers/dist/wordlist-zh' {
  declare module.exports: any;
}

declare module 'ethers/errors' {
  declare module.exports: any;
}

declare module 'ethers/ethers' {
  declare module.exports: any;
}

declare module 'ethers/gulpfile' {
  declare module.exports: any;
}

declare module 'ethers/providers/abstract-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/base-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/etherscan-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/fallback-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/index' {
  declare module.exports: any;
}

declare module 'ethers/providers/infura-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/ipc-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/json-rpc-provider' {
  declare module.exports: any;
}

declare module 'ethers/providers/web3-provider' {
  declare module.exports: any;
}

declare module 'ethers/shims/base64' {
  declare module.exports: any;
}

declare module 'ethers/shims/empty' {
  declare module.exports: any;
}

declare module 'ethers/shims/hmac' {
  declare module.exports: any;
}

declare module 'ethers/shims/index' {
  declare module.exports: any;
}

declare module 'ethers/shims/pbkdf2' {
  declare module.exports: any;
}

declare module 'ethers/shims/random-bytes' {
  declare module.exports: any;
}

declare module 'ethers/shims/shims' {
  declare module.exports: any;
}

declare module 'ethers/shims/wordlists' {
  declare module.exports: any;
}

declare module 'ethers/shims/xmlhttprequest' {
  declare module.exports: any;
}

declare module 'ethers/tests/browser' {
  declare module.exports: any;
}

declare module 'ethers/tests/deploy-test-contract' {
  declare module.exports: any;
}

declare module 'ethers/tests/local-tests' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-accounts' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-contract-events' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-contract-interface' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-contract-signatures' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-hashes' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-hdnode' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-providers' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-rlpcoder' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-transactions' {
  declare module.exports: any;
}

declare module 'ethers/tests/make-tests/make-wallets' {
  declare module.exports: any;
}

declare module 'ethers/tests/reporter' {
  declare module.exports: any;
}

declare module 'ethers/tests/run-providers' {
  declare module.exports: any;
}

declare module 'ethers/tests/run-testrpc' {
  declare module.exports: any;
}

declare module 'ethers/tests/shims/base64' {
  declare module.exports: any;
}

declare module 'ethers/tests/shims/es6-promise.auto' {
  declare module.exports: any;
}

declare module 'ethers/tests/shims/index' {
  declare module.exports: any;
}

declare module 'ethers/tests/shims/unorm' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-account' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-build' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-contract-interface' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-contract' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-hdnode' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-providers' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-utils' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-wallet' {
  declare module.exports: any;
}

declare module 'ethers/tests/test-wordlists' {
  declare module.exports: any;
}

declare module 'ethers/tests/utils-ethers-browser' {
  declare module.exports: any;
}

declare module 'ethers/tests/utils-ethers' {
  declare module.exports: any;
}

declare module 'ethers/tests/utils' {
  declare module.exports: any;
}

declare module 'ethers/tests/wordlist-generation/analyse-es' {
  declare module.exports: any;
}

declare module 'ethers/tests/wordlist-generation/analyse-fr' {
  declare module.exports: any;
}

declare module 'ethers/tests/wordlist-generation/analyse-it' {
  declare module.exports: any;
}

declare module 'ethers/tests/wordlist-generation/analyse-ja' {
  declare module.exports: any;
}

declare module 'ethers/tests/wordlist-generation/analyse-ko' {
  declare module.exports: any;
}

declare module 'ethers/tests/wordlist-generation/analyse-zh' {
  declare module.exports: any;
}

declare module 'ethers/utils/abi-coder' {
  declare module.exports: any;
}

declare module 'ethers/utils/address' {
  declare module.exports: any;
}

declare module 'ethers/utils/base64' {
  declare module.exports: any;
}

declare module 'ethers/utils/basex' {
  declare module.exports: any;
}

declare module 'ethers/utils/bignumber' {
  declare module.exports: any;
}

declare module 'ethers/utils/bytes' {
  declare module.exports: any;
}

declare module 'ethers/utils/hash' {
  declare module.exports: any;
}

declare module 'ethers/utils/hdnode' {
  declare module.exports: any;
}

declare module 'ethers/utils/hmac' {
  declare module.exports: any;
}

declare module 'ethers/utils/index' {
  declare module.exports: any;
}

declare module 'ethers/utils/interface' {
  declare module.exports: any;
}

declare module 'ethers/utils/json-wallet' {
  declare module.exports: any;
}

declare module 'ethers/utils/keccak256' {
  declare module.exports: any;
}

declare module 'ethers/utils/networks' {
  declare module.exports: any;
}

declare module 'ethers/utils/pbkdf2' {
  declare module.exports: any;
}

declare module 'ethers/utils/properties' {
  declare module.exports: any;
}

declare module 'ethers/utils/random-bytes' {
  declare module.exports: any;
}

declare module 'ethers/utils/rlp' {
  declare module.exports: any;
}

declare module 'ethers/utils/secp256k1' {
  declare module.exports: any;
}

declare module 'ethers/utils/secret-storage' {
  declare module.exports: any;
}

declare module 'ethers/utils/sha2' {
  declare module.exports: any;
}

declare module 'ethers/utils/shims' {
  declare module.exports: any;
}

declare module 'ethers/utils/signing-key' {
  declare module.exports: any;
}

declare module 'ethers/utils/solidity' {
  declare module.exports: any;
}

declare module 'ethers/utils/transaction' {
  declare module.exports: any;
}

declare module 'ethers/utils/units' {
  declare module.exports: any;
}

declare module 'ethers/utils/utf8' {
  declare module.exports: any;
}

declare module 'ethers/utils/web' {
  declare module.exports: any;
}

declare module 'ethers/utils/wordlist' {
  declare module.exports: any;
}

declare module 'ethers/wallet' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/index' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-en' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-es' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-fr' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-it' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-ja' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-ko' {
  declare module.exports: any;
}

declare module 'ethers/wordlists/lang-zh' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethers/_version.js' {
  declare module.exports: $Exports<'ethers/_version'>;
}
declare module 'ethers/abstract-signer.js' {
  declare module.exports: $Exports<'ethers/abstract-signer'>;
}
declare module 'ethers/constants.js' {
  declare module.exports: $Exports<'ethers/constants'>;
}
declare module 'ethers/contract.js' {
  declare module.exports: $Exports<'ethers/contract'>;
}
declare module 'ethers/dist/ethers.js' {
  declare module.exports: $Exports<'ethers/dist/ethers'>;
}
declare module 'ethers/dist/ethers.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.min'>;
}
declare module 'ethers/dist/shims.js' {
  declare module.exports: $Exports<'ethers/dist/shims'>;
}
declare module 'ethers/dist/wordlist-es.js' {
  declare module.exports: $Exports<'ethers/dist/wordlist-es'>;
}
declare module 'ethers/dist/wordlist-fr.js' {
  declare module.exports: $Exports<'ethers/dist/wordlist-fr'>;
}
declare module 'ethers/dist/wordlist-it.js' {
  declare module.exports: $Exports<'ethers/dist/wordlist-it'>;
}
declare module 'ethers/dist/wordlist-ja.js' {
  declare module.exports: $Exports<'ethers/dist/wordlist-ja'>;
}
declare module 'ethers/dist/wordlist-ko.js' {
  declare module.exports: $Exports<'ethers/dist/wordlist-ko'>;
}
declare module 'ethers/dist/wordlist-zh.js' {
  declare module.exports: $Exports<'ethers/dist/wordlist-zh'>;
}
declare module 'ethers/errors.js' {
  declare module.exports: $Exports<'ethers/errors'>;
}
declare module 'ethers/ethers.js' {
  declare module.exports: $Exports<'ethers/ethers'>;
}
declare module 'ethers/gulpfile.js' {
  declare module.exports: $Exports<'ethers/gulpfile'>;
}
declare module 'ethers/index' {
  declare module.exports: $Exports<'ethers'>;
}
declare module 'ethers/index.js' {
  declare module.exports: $Exports<'ethers'>;
}
declare module 'ethers/providers/abstract-provider.js' {
  declare module.exports: $Exports<'ethers/providers/abstract-provider'>;
}
declare module 'ethers/providers/base-provider.js' {
  declare module.exports: $Exports<'ethers/providers/base-provider'>;
}
declare module 'ethers/providers/etherscan-provider.js' {
  declare module.exports: $Exports<'ethers/providers/etherscan-provider'>;
}
declare module 'ethers/providers/fallback-provider.js' {
  declare module.exports: $Exports<'ethers/providers/fallback-provider'>;
}
declare module 'ethers/providers/index.js' {
  declare module.exports: $Exports<'ethers/providers/index'>;
}
declare module 'ethers/providers/infura-provider.js' {
  declare module.exports: $Exports<'ethers/providers/infura-provider'>;
}
declare module 'ethers/providers/ipc-provider.js' {
  declare module.exports: $Exports<'ethers/providers/ipc-provider'>;
}
declare module 'ethers/providers/json-rpc-provider.js' {
  declare module.exports: $Exports<'ethers/providers/json-rpc-provider'>;
}
declare module 'ethers/providers/web3-provider.js' {
  declare module.exports: $Exports<'ethers/providers/web3-provider'>;
}
declare module 'ethers/shims/base64.js' {
  declare module.exports: $Exports<'ethers/shims/base64'>;
}
declare module 'ethers/shims/empty.js' {
  declare module.exports: $Exports<'ethers/shims/empty'>;
}
declare module 'ethers/shims/hmac.js' {
  declare module.exports: $Exports<'ethers/shims/hmac'>;
}
declare module 'ethers/shims/index.js' {
  declare module.exports: $Exports<'ethers/shims/index'>;
}
declare module 'ethers/shims/pbkdf2.js' {
  declare module.exports: $Exports<'ethers/shims/pbkdf2'>;
}
declare module 'ethers/shims/random-bytes.js' {
  declare module.exports: $Exports<'ethers/shims/random-bytes'>;
}
declare module 'ethers/shims/shims.js' {
  declare module.exports: $Exports<'ethers/shims/shims'>;
}
declare module 'ethers/shims/wordlists.js' {
  declare module.exports: $Exports<'ethers/shims/wordlists'>;
}
declare module 'ethers/shims/xmlhttprequest.js' {
  declare module.exports: $Exports<'ethers/shims/xmlhttprequest'>;
}
declare module 'ethers/tests/browser.js' {
  declare module.exports: $Exports<'ethers/tests/browser'>;
}
declare module 'ethers/tests/deploy-test-contract.js' {
  declare module.exports: $Exports<'ethers/tests/deploy-test-contract'>;
}
declare module 'ethers/tests/local-tests.js' {
  declare module.exports: $Exports<'ethers/tests/local-tests'>;
}
declare module 'ethers/tests/make-tests/make-accounts.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-accounts'>;
}
declare module 'ethers/tests/make-tests/make-contract-events.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-contract-events'>;
}
declare module 'ethers/tests/make-tests/make-contract-interface.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-contract-interface'>;
}
declare module 'ethers/tests/make-tests/make-contract-signatures.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-contract-signatures'>;
}
declare module 'ethers/tests/make-tests/make-hashes.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-hashes'>;
}
declare module 'ethers/tests/make-tests/make-hdnode.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-hdnode'>;
}
declare module 'ethers/tests/make-tests/make-providers.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-providers'>;
}
declare module 'ethers/tests/make-tests/make-rlpcoder.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-rlpcoder'>;
}
declare module 'ethers/tests/make-tests/make-transactions.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-transactions'>;
}
declare module 'ethers/tests/make-tests/make-wallets.js' {
  declare module.exports: $Exports<'ethers/tests/make-tests/make-wallets'>;
}
declare module 'ethers/tests/reporter.js' {
  declare module.exports: $Exports<'ethers/tests/reporter'>;
}
declare module 'ethers/tests/run-providers.js' {
  declare module.exports: $Exports<'ethers/tests/run-providers'>;
}
declare module 'ethers/tests/run-testrpc.js' {
  declare module.exports: $Exports<'ethers/tests/run-testrpc'>;
}
declare module 'ethers/tests/shims/base64.js' {
  declare module.exports: $Exports<'ethers/tests/shims/base64'>;
}
declare module 'ethers/tests/shims/es6-promise.auto.js' {
  declare module.exports: $Exports<'ethers/tests/shims/es6-promise.auto'>;
}
declare module 'ethers/tests/shims/index.js' {
  declare module.exports: $Exports<'ethers/tests/shims/index'>;
}
declare module 'ethers/tests/shims/unorm.js' {
  declare module.exports: $Exports<'ethers/tests/shims/unorm'>;
}
declare module 'ethers/tests/test-account.js' {
  declare module.exports: $Exports<'ethers/tests/test-account'>;
}
declare module 'ethers/tests/test-build.js' {
  declare module.exports: $Exports<'ethers/tests/test-build'>;
}
declare module 'ethers/tests/test-contract-interface.js' {
  declare module.exports: $Exports<'ethers/tests/test-contract-interface'>;
}
declare module 'ethers/tests/test-contract.js' {
  declare module.exports: $Exports<'ethers/tests/test-contract'>;
}
declare module 'ethers/tests/test-hdnode.js' {
  declare module.exports: $Exports<'ethers/tests/test-hdnode'>;
}
declare module 'ethers/tests/test-providers.js' {
  declare module.exports: $Exports<'ethers/tests/test-providers'>;
}
declare module 'ethers/tests/test-utils.js' {
  declare module.exports: $Exports<'ethers/tests/test-utils'>;
}
declare module 'ethers/tests/test-wallet.js' {
  declare module.exports: $Exports<'ethers/tests/test-wallet'>;
}
declare module 'ethers/tests/test-wordlists.js' {
  declare module.exports: $Exports<'ethers/tests/test-wordlists'>;
}
declare module 'ethers/tests/utils-ethers-browser.js' {
  declare module.exports: $Exports<'ethers/tests/utils-ethers-browser'>;
}
declare module 'ethers/tests/utils-ethers.js' {
  declare module.exports: $Exports<'ethers/tests/utils-ethers'>;
}
declare module 'ethers/tests/utils.js' {
  declare module.exports: $Exports<'ethers/tests/utils'>;
}
declare module 'ethers/tests/wordlist-generation/analyse-es.js' {
  declare module.exports: $Exports<'ethers/tests/wordlist-generation/analyse-es'>;
}
declare module 'ethers/tests/wordlist-generation/analyse-fr.js' {
  declare module.exports: $Exports<'ethers/tests/wordlist-generation/analyse-fr'>;
}
declare module 'ethers/tests/wordlist-generation/analyse-it.js' {
  declare module.exports: $Exports<'ethers/tests/wordlist-generation/analyse-it'>;
}
declare module 'ethers/tests/wordlist-generation/analyse-ja.js' {
  declare module.exports: $Exports<'ethers/tests/wordlist-generation/analyse-ja'>;
}
declare module 'ethers/tests/wordlist-generation/analyse-ko.js' {
  declare module.exports: $Exports<'ethers/tests/wordlist-generation/analyse-ko'>;
}
declare module 'ethers/tests/wordlist-generation/analyse-zh.js' {
  declare module.exports: $Exports<'ethers/tests/wordlist-generation/analyse-zh'>;
}
declare module 'ethers/utils/abi-coder.js' {
  declare module.exports: $Exports<'ethers/utils/abi-coder'>;
}
declare module 'ethers/utils/address.js' {
  declare module.exports: $Exports<'ethers/utils/address'>;
}
declare module 'ethers/utils/base64.js' {
  declare module.exports: $Exports<'ethers/utils/base64'>;
}
declare module 'ethers/utils/basex.js' {
  declare module.exports: $Exports<'ethers/utils/basex'>;
}
declare module 'ethers/utils/bignumber.js' {
  declare module.exports: $Exports<'ethers/utils/bignumber'>;
}
declare module 'ethers/utils/bytes.js' {
  declare module.exports: $Exports<'ethers/utils/bytes'>;
}
declare module 'ethers/utils/hash.js' {
  declare module.exports: $Exports<'ethers/utils/hash'>;
}
declare module 'ethers/utils/hdnode.js' {
  declare module.exports: $Exports<'ethers/utils/hdnode'>;
}
declare module 'ethers/utils/hmac.js' {
  declare module.exports: $Exports<'ethers/utils/hmac'>;
}
declare module 'ethers/utils/index.js' {
  declare module.exports: $Exports<'ethers/utils/index'>;
}
declare module 'ethers/utils/interface.js' {
  declare module.exports: $Exports<'ethers/utils/interface'>;
}
declare module 'ethers/utils/json-wallet.js' {
  declare module.exports: $Exports<'ethers/utils/json-wallet'>;
}
declare module 'ethers/utils/keccak256.js' {
  declare module.exports: $Exports<'ethers/utils/keccak256'>;
}
declare module 'ethers/utils/networks.js' {
  declare module.exports: $Exports<'ethers/utils/networks'>;
}
declare module 'ethers/utils/pbkdf2.js' {
  declare module.exports: $Exports<'ethers/utils/pbkdf2'>;
}
declare module 'ethers/utils/properties.js' {
  declare module.exports: $Exports<'ethers/utils/properties'>;
}
declare module 'ethers/utils/random-bytes.js' {
  declare module.exports: $Exports<'ethers/utils/random-bytes'>;
}
declare module 'ethers/utils/rlp.js' {
  declare module.exports: $Exports<'ethers/utils/rlp'>;
}
declare module 'ethers/utils/secp256k1.js' {
  declare module.exports: $Exports<'ethers/utils/secp256k1'>;
}
declare module 'ethers/utils/secret-storage.js' {
  declare module.exports: $Exports<'ethers/utils/secret-storage'>;
}
declare module 'ethers/utils/sha2.js' {
  declare module.exports: $Exports<'ethers/utils/sha2'>;
}
declare module 'ethers/utils/shims.js' {
  declare module.exports: $Exports<'ethers/utils/shims'>;
}
declare module 'ethers/utils/signing-key.js' {
  declare module.exports: $Exports<'ethers/utils/signing-key'>;
}
declare module 'ethers/utils/solidity.js' {
  declare module.exports: $Exports<'ethers/utils/solidity'>;
}
declare module 'ethers/utils/transaction.js' {
  declare module.exports: $Exports<'ethers/utils/transaction'>;
}
declare module 'ethers/utils/units.js' {
  declare module.exports: $Exports<'ethers/utils/units'>;
}
declare module 'ethers/utils/utf8.js' {
  declare module.exports: $Exports<'ethers/utils/utf8'>;
}
declare module 'ethers/utils/web.js' {
  declare module.exports: $Exports<'ethers/utils/web'>;
}
declare module 'ethers/utils/wordlist.js' {
  declare module.exports: $Exports<'ethers/utils/wordlist'>;
}
declare module 'ethers/wallet.js' {
  declare module.exports: $Exports<'ethers/wallet'>;
}
declare module 'ethers/wordlists/index.js' {
  declare module.exports: $Exports<'ethers/wordlists/index'>;
}
declare module 'ethers/wordlists/lang-en.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-en'>;
}
declare module 'ethers/wordlists/lang-es.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-es'>;
}
declare module 'ethers/wordlists/lang-fr.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-fr'>;
}
declare module 'ethers/wordlists/lang-it.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-it'>;
}
declare module 'ethers/wordlists/lang-ja.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-ja'>;
}
declare module 'ethers/wordlists/lang-ko.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-ko'>;
}
declare module 'ethers/wordlists/lang-zh.js' {
  declare module.exports: $Exports<'ethers/wordlists/lang-zh'>;
}
