// flow-typed signature: ceb13d56fccc2bac51ae3b7ad8fb9304
// flow-typed version: <<STUB>>/react-native-dotenv_v^0.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-dotenv/index' {
  declare module.exports: $Exports<'react-native-dotenv'>;
}
declare module 'react-native-dotenv/index.js' {
  declare module.exports: $Exports<'react-native-dotenv'>;
}
