export enum ReduxFirestoreType {
  SEND_DATA_TO_FIRESTORE = 'SEND_DATA_TO_FIRESTORE',
  DATA_SENT_TO_FIRESTORE = 'DATA_SENT_TO_FIRESTORE',
  SEND_DATA_TO_FIRESTORE_ERROR = 'SEND_DATA_TO_FIRESTORE_ERROR',
}
