export enum ReduxGasThresholdType {
  FETCH_GAS_THRESHOLDS = 'FETCH_GAS_THRESHOLDS',
  GAS_THRESHOLDS_FETCHED = 'GAS_THRESHOLDS_FETCHED',
  FETCH_GAS_THRESHOLDS_ERROR = 'FETCH_GAS_THRESHOLDS_ERROR',
}
