export enum ReduxNativeIntegrationType {
  FETCH_NATIVE_INTEGRATION = 'FETCH_NATIVE_INTEGRATION',
  NATIVE_INTEGRATION_FETCHED = 'NATIVE_INTEGRATION_FETCHED',
  FETCH_NATIVE_INTEGRATION_ERROR = 'FETCH_NATIVE_INTEGRATION_ERROR',
}
