export enum ReduxNativeIntegrationType {
  FETCH_NATIVE_INTEGRATION_ABIS = 'FETCH_NATIVE_INTEGRATION_ABIS',
  NATIVE_INTEGRATION_ABIS_FETCHED = 'NATIVE_INTEGRATION_ABIS_FETCHED',
  FETCH_NATIVE_INTEGRATION_ABIS_ERROR = 'FETCH_NATIVE_INTEGRATION_ABIS_ERROR',
}
