// @flow
export const UPDATE_BADGES = 'UPDATE_BADGES';
export const ADD_CONTACT_BADGES = 'ADD_CONTACT_BADGES';
export const SET_CONTACTS_BADGES = 'SET_CONTACTS_BADGES';
export const FETCHING_CONTACTS_BADGES = 'FETCHING_CONTACTS_BADGES';
export const STOP_FETCHING_CONTACTS_BADGES = 'STOP_FETCHING_CONTACTS_BADGES';
export const BADGE_REWARD_EVENT = 'badgeAwardConfirmationEvent';
export const SET_BADGE_AWARD_EVENTS = 'SET_BADGE_AWARD_EVENTS';
