// @flow
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_CHATS = 'UPDATE_CHATS';
export const FETCHING_CHATS = 'FETCHING_CHATS';
export const RESET_UNREAD_MESSAGE = 'RESET_UNREAD_MESSAGE';
export const CHAT = 'CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const ADD_WEBSOCKET_SENT_MESSAGE = 'ADD_WEBSOCKET_SENT_MESSAGE';
export const ADD_WEBSOCKET_RECEIVED_MESSAGE = 'ADD_WEBSOCKET_RECEIVED_MESSAGE';
export const REMOVE_WEBSOCKET_SENT_MESSAGE = 'REMOVE_WEBSOCKET_SENT_MESSAGE';
export const REMOVE_WEBSOCKET_RECEIVED_USER_MESSAGES = 'REMOVE_WEBSOCKET_RECEIVED_USER_MESSAGES';
export const DELETE_CONTACT = 'DELETE_CONTACT';
