// @flow
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_CHATS = 'UPDATE_CHATS';
export const FETCHING_CHATS = 'FETCHING_CHATS';
export const RESET_UNREAD_MESSAGE = 'RESET_UNREAD_MESSAGE';
export const CHAT = 'CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
export const NEW_WEBSOCKET_MESSAGE = 'NEW_WEBSOCKET_MESSAGE';
export const RESET_WEBSOCKET_MESSAGES = 'RESET_WEBSOCKET_MESSAGES';
