// @flow

export const CONNEXT_INIT_CHANNEL_PENDING = 'CONNEXT_INIT_CHANNEL_PENDING';
export const CONNEXT_INIT_CHANNEL_SUCCESS = 'CONNEXT_INIT_CHANNEL_SUCCESS';
export const CONNEXT_INIT_CHANNEL_FAILURE = 'CONNEXT_INIT_CHANNEL_FAILURE';
