// @flow
export const TRANSACTION_SENT = 'TRANSACTION_SENT';
export const TRANSACTION_SENT_PENDING = 'TRANSACTION_SENT_PENDING';
export const TRANSACTION_RECEIVED = 'TRANSACTION_RECEIVED';
export const TRANSACTION_RECEIVED_PENDING = 'TRANSACTION_RECEIVED_PENDING';
export const CONNECTION_INCOMING = 'CONNECTION_INCOMING';
export const CONNECTION_SENT = 'CONNECTION_SENT';
export const CONNECTION_MADE = 'CONNECTION_MADE';
