// @flow

export const ADD_INVITATION = 'ADD_INVITATION';
export const UPDATE_INVITATIONS = 'UPDATE_INVITATIONS';
export const UPDATE_INVITATIONS_STATE = 'UPDATE_INVITATIONS_STATE';
export const TYPE_SENT = 'TYPE_SENT';
export const TYPE_RECEIVED = 'TYPE_RECEIVED';
