// @flow

// APP FLOW
export const APP_FLOW = 'APP_FLOW';
export const TAB_NAVIGATION = 'TAB_NAVIGATION';
export const ASSETS = 'ASSETS';
export const ASSET = 'ASSET';
export const ICO = 'ICO';
export const ADD_TOKEN = 'ADD_TOKEN';
export const PROFILE = 'PROFILE';
export const REVEAL_BACKUP_PHRASE = 'REVEAL_BACKUP_PHRASE';

// CHANGE PIN FLOW
export const CHANGE_PIN_FLOW = 'CHANGE_PIN_FLOW';
export const CHANGE_PIN_CURRENT_PIN = 'CHANGE_PIN_CURRENT_PIN';
export const CHANGE_PIN_NEW_PIN = 'CHANGE_PIN_NEW_PIN';
export const CHANGE_PIN_CONFIRM_NEW_PIN = 'CHANGE_PIN_CONFIRM_NEW_PIN';

// ONBOARDING FLOW
export const ONBOARDING_FLOW = 'ONBOARDING_FLOW';
export const ONBOARDING_HOME = 'ONBOARDING_HOME';
export const NEW_WALLET = 'NEW_WALLET';
export const NEW_PROFILE = 'NEW_PROFILE';
export const IMPORT_WALLET = 'IMPORT_WALLET';
export const BACKUP_PHRASE = 'BACKUP_PHRASE';
export const BACKUP_PHRASE_VALIDATE = 'BACKUP_PHRASE_VALIDATE';
export const SET_WALLET_PIN_CODE = 'SET_WALLET_PIN_CODE';
export const PIN_CODE_CONFIRMATION = 'PIN_CODE_CONFIRMATION';
export const LEGAL_TERMS = 'LEGAL_TERMS';

// PINCODE FLOW
export const AUTH_FLOW = 'AUTH_FLOW';
export const PIN_CODE_UNLOCK = 'PIN_CODE_UNLOCK';

// SIGNUP/OTP FLOW
export const SECURITY_CONFIRM = 'SECURITY_CONFIRM';
export const SIGN_UP_FLOW = 'SIGN_UP_FLOW';
export const WELCOME = 'WELCOME';
export const SIGN_IN = 'SIGN_IN';
export const OTP = 'OTP';
export const OTP_STATUS = 'OTP_STATUS';
export const SIGN_UP = 'SIGN_UP';

// SEND TOKEN FLOW
export const SEND_TOKEN_FLOW = 'SEND_TOKEN_FLOW';
export const SEND_TOKEN_AMOUNT = 'SEND_TOKEN_AMOUNT';
export const SEND_TOKEN_CONTACTS = 'SEND_TOKEN_CONTACTS';
export const SEND_TOKEN_CONFIRM = 'SEND_TOKEN_CONFIRM';
