// @flow
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const UPDATE_INTERCOM_NOTIFICATIONS_COUNT = 'UPDATE_INTERCOM_NOTIFICATIONS_COUNT';
export const SET_UNREAD_NOTIFICATIONS_STATUS = 'SET_UNREAD_NOTIFICATIONS_STATUS';
