// @flow
export const GET_OCEAN_DATA_SETS_START = 'GET_OCEAN_DATA_SETS_START';
export const GET_OCEAN_DATA_SETS = 'GET_OCEAN_DATA_SETS';
export const GET_OCEAN_DATA_SETS_ERROR = 'GET_OCEAN_DATA_SETS_ERROR';

export const TRANSFER_OCEAN_TOKEN_START = 'TRANSFER_OCEAN_TOKEN_START';
export const TRANSFER_OCEAN_TOKEN = 'TRANSFER_OCEAN_TOKEN';
export const TRANSFER_OCEAN_TOKEN_ERROR = 'TRANSFER_OCEAN_TOKEN_ERROR';
