export const TRANSACTION_STATUS = {
  UNSENT: 'UNSENT',
  PENDING: 'PENDING',
  RECEIVING: 'RECEIVING',
  ESTIMATING: 'ESTIMATING',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
  REJECTED_BY_USER: 'REJECTED_BY_USER',
};
