// @flow
export const GENERATE_ENCRYPTED_WALLET = 'GENERATE_ENCRYPTED_WALLET';
export const UPDATE_WALLET_MNEMONIC = 'UPDATE_WALLET_MNEMONIC';
export const UPDATE_WALLET_STATE = 'UPDATE_WALLET_STATE';
export const DECRYPT_WALLET = 'DECRYPT_WALLET';
export const CREATED = 'CREATED';
export const GENERATING = 'GENERATING';
export const ENCRYPTING = 'ENCRYPTING';
export const DECRYPTING = 'DECRYPTING';
export const DECRYPTED = 'DECRYPTED';
export const EXISTS = 'EXISTS';
export const EMPTY = 'EMPTY';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const IMPORT_ERROR = 'IMPORT_ERROR';
export const IMPORT_SET_PIN = 'IMPORT_SET_PIN';
export const IMPORTED = 'IMPORTED';
export const SET_WALLET_ERROR = 'SET_WALLET_ERROR';
export const WALLET_ERROR = 'WALLET_ERROR';
