export const GENERATE_ENCRYPTED_WALLET = 'GENERATE_ENCRYPTED_WALLET';
export const UPDATE_WALLET_STATE = 'UPDATE_WALLET_STATE'

export const CREATED = 'CREATED';
export const GENERATING = 'GENERATING';
export const ENCRYPTING = 'ENCRYPTING';
