source "https://rubygems.org"
gem 'rake'
gem "fastlane", "2.162.0"
gem 'fastlane-plugin-get_version_name'
gem 'fastlane-plugin-property_file_read'
gem 'fastlane-plugin-appcenter'
gem 'indentation', '~> 0.1.1'
gem 'tiny_png_checker', '~> 0.1.2'
gem "xcode-install"
gem 'cocoapods', '= 1.9.1'
gem 'cocoapods-check', '~> 1.0', '>= 1.0.2'
