source "https://rubygems.org"

require 'logger'

gem 'rake'
# https://github.com/fastlane/fastlane/issues/21794
gem 'rb-readline'
gem "fastlane"
gem 'fastlane-plugin-get_version_name'
gem 'fastlane-plugin-property_file_read'
gem 'fastlane-plugin-appcenter'
gem 'indentation', '~> 0.1.1'
gem 'tiny_png_checker', '~> 0.1.2'
gem "xcode-install"
gem 'cocoapods', '>= 1.14', '!= 1.15.0', '!= 1.15.1'
gem 'cocoapods-check', '~> 1.0', '>= 1.0.2'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'