require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pillarwallet' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

    # Fix xcodebuild "supported deployment target" warnings
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          ## Keep in sync with pbxproj!
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0' 
        end
      end
  end

  ### Custom Pods
  
  # pod for splash gif
  pod 'SwiftyGif'
  
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # react-native-permissions:
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
end
