// flow-typed signature: ea43f3dbb9e27a3706bf80fadf7f4e34
// flow-typed version: <<STUB>>/@testing-library/jest-native_v5.4.3/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/jest-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/jest-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/jest-native/dist/__types__/jest-explicit-extend.test-d' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/__types__/jest-implicit-extend.test-d' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/component-tree' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/extend-expect' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/legacy-extend-expect' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-be-disabled' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-be-empty-element' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-be-on-the-screen' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-be-visible' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-contain-element' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-accessibility-state' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-accessibility-value' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-prop' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-style' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/to-have-text-content' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/dist/utils' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/extend-expect' {
  declare module.exports: any;
}

declare module '@testing-library/jest-native/legacy-extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/jest-native/dist/__types__/jest-explicit-extend.test-d.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/__types__/jest-explicit-extend.test-d'>;
}
declare module '@testing-library/jest-native/dist/__types__/jest-implicit-extend.test-d.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/__types__/jest-implicit-extend.test-d'>;
}
declare module '@testing-library/jest-native/dist/component-tree.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/component-tree'>;
}
declare module '@testing-library/jest-native/dist/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/extend-expect'>;
}
declare module '@testing-library/jest-native/dist/index' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist'>;
}
declare module '@testing-library/jest-native/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist'>;
}
declare module '@testing-library/jest-native/dist/legacy-extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/legacy-extend-expect'>;
}
declare module '@testing-library/jest-native/dist/to-be-disabled.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-be-disabled'>;
}
declare module '@testing-library/jest-native/dist/to-be-empty-element.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-be-empty-element'>;
}
declare module '@testing-library/jest-native/dist/to-be-on-the-screen.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-be-on-the-screen'>;
}
declare module '@testing-library/jest-native/dist/to-be-visible.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-be-visible'>;
}
declare module '@testing-library/jest-native/dist/to-contain-element.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-contain-element'>;
}
declare module '@testing-library/jest-native/dist/to-have-accessibility-state.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-accessibility-state'>;
}
declare module '@testing-library/jest-native/dist/to-have-accessibility-value.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-accessibility-value'>;
}
declare module '@testing-library/jest-native/dist/to-have-prop.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-prop'>;
}
declare module '@testing-library/jest-native/dist/to-have-style.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-style'>;
}
declare module '@testing-library/jest-native/dist/to-have-text-content.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/to-have-text-content'>;
}
declare module '@testing-library/jest-native/dist/utils.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/dist/utils'>;
}
declare module '@testing-library/jest-native/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/extend-expect'>;
}
declare module '@testing-library/jest-native/legacy-extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/jest-native/legacy-extend-expect'>;
}
