// flow-typed signature: 99fb00a396e4bc37e8ac5a278367a87f
// flow-typed version: <<STUB>>/@testing-library/react-native_v13.2.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react-native/build/act' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/cleanup' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/config' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/event-handler' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/fire-event' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/flush-micro-tasks' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/accessibility' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/component-tree' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/debug' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/ensure-peer-deps' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/errors' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/find-all' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/format-element' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/host-component-names' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/logger' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/map-props' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-accessibility-state' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-accessibility-value' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-array-prop' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-label-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-object-prop' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-string-prop' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/matchers/match-text-content' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/object' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/pointer-events' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/string-validation' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/text-content' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/text-input' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/timers' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/helpers/wrap-async' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/index.flow' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/extend-expect' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-busy' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-checked' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-disabled' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-empty-element' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-expanded' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-on-the-screen' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-partially-checked' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-selected' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-be-visible' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-contain-element' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-have-accessibility-value' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-have-accessible-name' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-have-display-value' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-have-prop' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-have-style' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/to-have-text-content' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/types' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matchers/utils' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/matches' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/native-state' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/display-value' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/hint-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/label-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/make-queries' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/options' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/placeholder-text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/role' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/test-id' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/text' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/unsafe-props' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/queries/unsafe-type' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/react-versions' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/render-act' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/render-hook' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/render' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/screen' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/test-utils/events' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/test-utils' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/types' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/clear' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/event-builder/base' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/event-builder/common' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/event-builder' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/event-builder/scroll-view' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/event-builder/text-input' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/paste' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/press' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/press/press' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/scroll' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/scroll/scroll-to' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/scroll/utils' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/setup' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/setup/setup' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/type' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/type/parse-keys' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/type/type' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/utils/content-size' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/utils/dispatch-event' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/utils' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/utils/text-range' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/user-event/utils/wait' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/wait-for-element-to-be-removed' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/wait-for' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/build/within' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/dont-cleanup-after-each' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/matchers' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-native/typings/index.flow' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react-native/build/act.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/act'>;
}
declare module '@testing-library/react-native/build/cleanup.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/cleanup'>;
}
declare module '@testing-library/react-native/build/config.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/config'>;
}
declare module '@testing-library/react-native/build/event-handler.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/event-handler'>;
}
declare module '@testing-library/react-native/build/fire-event.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/fire-event'>;
}
declare module '@testing-library/react-native/build/flush-micro-tasks.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/flush-micro-tasks'>;
}
declare module '@testing-library/react-native/build/helpers/accessibility.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/accessibility'>;
}
declare module '@testing-library/react-native/build/helpers/component-tree.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/component-tree'>;
}
declare module '@testing-library/react-native/build/helpers/debug.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/debug'>;
}
declare module '@testing-library/react-native/build/helpers/ensure-peer-deps.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/ensure-peer-deps'>;
}
declare module '@testing-library/react-native/build/helpers/errors.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/errors'>;
}
declare module '@testing-library/react-native/build/helpers/find-all.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/find-all'>;
}
declare module '@testing-library/react-native/build/helpers/format-element.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/format-element'>;
}
declare module '@testing-library/react-native/build/helpers/host-component-names.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/host-component-names'>;
}
declare module '@testing-library/react-native/build/helpers/logger.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/logger'>;
}
declare module '@testing-library/react-native/build/helpers/map-props.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/map-props'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-accessibility-state.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-accessibility-state'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-accessibility-value.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-accessibility-value'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-array-prop.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-array-prop'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-label-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-label-text'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-object-prop.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-object-prop'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-string-prop.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-string-prop'>;
}
declare module '@testing-library/react-native/build/helpers/matchers/match-text-content.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/matchers/match-text-content'>;
}
declare module '@testing-library/react-native/build/helpers/object.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/object'>;
}
declare module '@testing-library/react-native/build/helpers/pointer-events.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/pointer-events'>;
}
declare module '@testing-library/react-native/build/helpers/string-validation.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/string-validation'>;
}
declare module '@testing-library/react-native/build/helpers/text-content.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/text-content'>;
}
declare module '@testing-library/react-native/build/helpers/text-input.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/text-input'>;
}
declare module '@testing-library/react-native/build/helpers/timers.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/timers'>;
}
declare module '@testing-library/react-native/build/helpers/wrap-async.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/helpers/wrap-async'>;
}
declare module '@testing-library/react-native/build/index.flow.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/index.flow'>;
}
declare module '@testing-library/react-native/build/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build'>;
}
declare module '@testing-library/react-native/build/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build'>;
}
declare module '@testing-library/react-native/build/matchers/extend-expect.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/extend-expect'>;
}
declare module '@testing-library/react-native/build/matchers/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers'>;
}
declare module '@testing-library/react-native/build/matchers/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-busy.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-busy'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-checked.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-checked'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-disabled.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-disabled'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-empty-element.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-empty-element'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-expanded.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-expanded'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-on-the-screen.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-on-the-screen'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-partially-checked.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-partially-checked'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-selected.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-selected'>;
}
declare module '@testing-library/react-native/build/matchers/to-be-visible.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-be-visible'>;
}
declare module '@testing-library/react-native/build/matchers/to-contain-element.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-contain-element'>;
}
declare module '@testing-library/react-native/build/matchers/to-have-accessibility-value.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-have-accessibility-value'>;
}
declare module '@testing-library/react-native/build/matchers/to-have-accessible-name.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-have-accessible-name'>;
}
declare module '@testing-library/react-native/build/matchers/to-have-display-value.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-have-display-value'>;
}
declare module '@testing-library/react-native/build/matchers/to-have-prop.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-have-prop'>;
}
declare module '@testing-library/react-native/build/matchers/to-have-style.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-have-style'>;
}
declare module '@testing-library/react-native/build/matchers/to-have-text-content.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/to-have-text-content'>;
}
declare module '@testing-library/react-native/build/matchers/types.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/types'>;
}
declare module '@testing-library/react-native/build/matchers/utils.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matchers/utils'>;
}
declare module '@testing-library/react-native/build/matches.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/matches'>;
}
declare module '@testing-library/react-native/build/native-state.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/native-state'>;
}
declare module '@testing-library/react-native/build/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/pure'>;
}
declare module '@testing-library/react-native/build/queries/display-value.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/display-value'>;
}
declare module '@testing-library/react-native/build/queries/hint-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/hint-text'>;
}
declare module '@testing-library/react-native/build/queries/label-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/label-text'>;
}
declare module '@testing-library/react-native/build/queries/make-queries.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/make-queries'>;
}
declare module '@testing-library/react-native/build/queries/options.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/options'>;
}
declare module '@testing-library/react-native/build/queries/placeholder-text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/placeholder-text'>;
}
declare module '@testing-library/react-native/build/queries/role.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/role'>;
}
declare module '@testing-library/react-native/build/queries/test-id.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/test-id'>;
}
declare module '@testing-library/react-native/build/queries/text.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/text'>;
}
declare module '@testing-library/react-native/build/queries/unsafe-props.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/unsafe-props'>;
}
declare module '@testing-library/react-native/build/queries/unsafe-type.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/queries/unsafe-type'>;
}
declare module '@testing-library/react-native/build/react-versions.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/react-versions'>;
}
declare module '@testing-library/react-native/build/render-act.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/render-act'>;
}
declare module '@testing-library/react-native/build/render-hook.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/render-hook'>;
}
declare module '@testing-library/react-native/build/render.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/render'>;
}
declare module '@testing-library/react-native/build/screen.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/screen'>;
}
declare module '@testing-library/react-native/build/test-utils/events.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/test-utils/events'>;
}
declare module '@testing-library/react-native/build/test-utils/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/test-utils'>;
}
declare module '@testing-library/react-native/build/test-utils/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/test-utils'>;
}
declare module '@testing-library/react-native/build/types.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/types'>;
}
declare module '@testing-library/react-native/build/user-event/clear.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/clear'>;
}
declare module '@testing-library/react-native/build/user-event/event-builder/base.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/event-builder/base'>;
}
declare module '@testing-library/react-native/build/user-event/event-builder/common.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/event-builder/common'>;
}
declare module '@testing-library/react-native/build/user-event/event-builder/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/event-builder'>;
}
declare module '@testing-library/react-native/build/user-event/event-builder/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/event-builder'>;
}
declare module '@testing-library/react-native/build/user-event/event-builder/scroll-view.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/event-builder/scroll-view'>;
}
declare module '@testing-library/react-native/build/user-event/event-builder/text-input.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/event-builder/text-input'>;
}
declare module '@testing-library/react-native/build/user-event/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event'>;
}
declare module '@testing-library/react-native/build/user-event/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event'>;
}
declare module '@testing-library/react-native/build/user-event/paste.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/paste'>;
}
declare module '@testing-library/react-native/build/user-event/press/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/press'>;
}
declare module '@testing-library/react-native/build/user-event/press/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/press'>;
}
declare module '@testing-library/react-native/build/user-event/press/press.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/press/press'>;
}
declare module '@testing-library/react-native/build/user-event/scroll/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/scroll'>;
}
declare module '@testing-library/react-native/build/user-event/scroll/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/scroll'>;
}
declare module '@testing-library/react-native/build/user-event/scroll/scroll-to.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/scroll/scroll-to'>;
}
declare module '@testing-library/react-native/build/user-event/scroll/utils.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/scroll/utils'>;
}
declare module '@testing-library/react-native/build/user-event/setup/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/setup'>;
}
declare module '@testing-library/react-native/build/user-event/setup/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/setup'>;
}
declare module '@testing-library/react-native/build/user-event/setup/setup.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/setup/setup'>;
}
declare module '@testing-library/react-native/build/user-event/type/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/type'>;
}
declare module '@testing-library/react-native/build/user-event/type/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/type'>;
}
declare module '@testing-library/react-native/build/user-event/type/parse-keys.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/type/parse-keys'>;
}
declare module '@testing-library/react-native/build/user-event/type/type.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/type/type'>;
}
declare module '@testing-library/react-native/build/user-event/utils/content-size.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/utils/content-size'>;
}
declare module '@testing-library/react-native/build/user-event/utils/dispatch-event.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/utils/dispatch-event'>;
}
declare module '@testing-library/react-native/build/user-event/utils/index' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/utils'>;
}
declare module '@testing-library/react-native/build/user-event/utils/index.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/utils'>;
}
declare module '@testing-library/react-native/build/user-event/utils/text-range.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/utils/text-range'>;
}
declare module '@testing-library/react-native/build/user-event/utils/wait.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/user-event/utils/wait'>;
}
declare module '@testing-library/react-native/build/wait-for-element-to-be-removed.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/wait-for-element-to-be-removed'>;
}
declare module '@testing-library/react-native/build/wait-for.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/wait-for'>;
}
declare module '@testing-library/react-native/build/within.js' {
  declare module.exports: $Exports<'@testing-library/react-native/build/within'>;
}
declare module '@testing-library/react-native/dont-cleanup-after-each.js' {
  declare module.exports: $Exports<'@testing-library/react-native/dont-cleanup-after-each'>;
}
declare module '@testing-library/react-native/matchers.js' {
  declare module.exports: $Exports<'@testing-library/react-native/matchers'>;
}
declare module '@testing-library/react-native/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-native/pure'>;
}
declare module '@testing-library/react-native/typings/index.flow.js' {
  declare module.exports: $Exports<'@testing-library/react-native/typings/index.flow'>;
}
