default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Create ios simulator build"
  lane :build_ios_simulator do
  match(type: "development",
        readonly: true)
        disable_automatic_code_signing(path: "pillarwallet.xcodeproj")
        xcbuild(
              workspace: "pillarwallet.xcworkspace",
              scheme: "pillarwallet",
              configuration: "Release",
              xcargs: "-sdk iphonesimulator SYMROOT='~/pillarwallet'"
          )
  zip(path: "/Users/distiller/pillarwallet/Release-iphonesimulator/pillarwallet.app",
      output_path: "./build/pillarwallet.app.zip"
    )
  end

  desc "Upload a new build to TestFlight"
  lane :build_test_flight do
    #sh "/usr/libexec/PlistBuddy -c 'Set :CFBundleVersion $CIRCLE_BUILD_NUM' ~/pillarwallet/ios/pillarwallet/Info.plist"
    match(type: "appstore",
          readonly: true)
    sh "xcodebuild -workspace ../pillarwallet.xcworkspace -configuration release -scheme pillarwallet -derivedDataPath ../build"
    sh "mkdir ../app && mkdir ../build/Build/Products/Release-iphoneos/Payload && cp -R ../build/Build/Products/Release-iphoneos/pillarwallet.app ../build/Build/Products/Release-iphoneos/Payload && mv ../build/Build/Products/Release-iphoneos/Payload ../app  && cp -R ../pillarwallet/SwiftSupport ../app && rm -rf ../build/Build/Products/Release-iphoneos/Payload/pillarwallet.app/libswiftRemoteMirror.dylib && /usr/bin/zip -r ../pillarwallet.ipa ../app"
    sigh(force: true)
    sh "fastlane sigh resign ../pillarwallet.ipa --signing_identity 'iPhone Distribution: PILLAR PROJECT WORLDWIDE LIMITED (J9DEY3FGPD)' --provisioning_profile '../AppStore_com.pillarproject.wallet.mobileprovision'"
    commit = last_git_commit
     upload_to_testflight(changelog: commit[:message],
     skip_waiting_for_build_processing: true,
    )
  end

  desc "Create a published build - ipa file"
  lane :build_ipa do
    match(type: "appstore",
          readonly: true)
    disable_automatic_code_signing(path: "pillarwallet.xcodeproj")
    build_app(clean: true,
              workspace: "pillarwallet.xcworkspace",
              scheme: "pillarwallet",
              configuration: "Release",
              export_method: "app-store"
    )
  end

end
