// @flow
export default [
  {
    symbol: 'PLR',
    name: 'Pillar',
    address: 'tokenAddress',
    description: 'tokenDescription',
    iconUrl: 'tokenIconUrl',
    iconMonoUrl: 'tokenIconMonoUrl',
    wallpaperUrl: 'tokenWallpaperUrl',
    decimals: 18,
  },
  {
    symbol: 'TOA',
    name: 'Token A',
    address: 'tokenAddress',
    description: 'tokenDescription',
    iconUrl: 'tokenIconUrl',
    iconMonoUrl: 'tokenIconMonoUrl',
    wallpaperUrl: 'tokenWallpaperUrl',
    decimals: 18,
  },
  {
    symbol: 'TOB',
    name: 'Token B',
    address: 'tokenAddress',
    description: 'tokenDescription',
    iconUrl: 'tokenIconUrl',
    iconMonoUrl: 'tokenIconMonoUrl',
    wallpaperUrl: 'tokenWallpaperUrl',
    decimals: 18,
  },
  {
    symbol: 'TOC',
    name: 'Token C',
    address: 'tokenAddress',
    description: 'tokenDescription',
    iconUrl: 'tokenIconUrl',
    iconMonoUrl: 'tokenIconMonoUrl',
    wallpaperUrl: 'tokenWallpaperUrl',
    decimals: 18,
  },
  {
    symbol: 'TOD',
    name: 'Token D',
    address: 'tokenAddress',
    description: 'tokenDescription',
    iconUrl: 'tokenIconUrl',
    iconMonoUrl: 'tokenIconMonoUrl',
    wallpaperUrl: 'tokenWallpaperUrl',
    decimals: 18,
  },
];
